config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: :show
  resources :museums, only: :show
  resources :collections, only: :show
  resources :submissions, only: :create
  resources :artefacts, only: [ :index, :show ] do
    member do
      post 'toggle_favorite', to: "artefacts#toggle_favorite"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artefact.rb
class Artefact < ApplicationRecord
  belongs_to :collection
  belongs_to :museum
  has_many :events
  has_many :favorites
  has_many :users, through: :favorites
  has_one_attached :photo

  validates :name, presence: true
  validates :origin_location, presence: true
  validates :current_location, presence: true

  acts_as_favoritable

  geocoded_by :current_location
  after_validation :geocode, if: :will_save_change_to_current_location?

  include PgSearch::Model
  multisearchable against: [ :name, :context, :made_by, :material ]
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :artefacts
  has_one_attached :photo

  validates :name, presence: true
  validates :period, presence: true
  validates :origin_location, presence: true

  geocoded_by :origin_location
  after_validation :geocode, if: :will_save_change_to_origin_location?

  include PgSearch::Model
  multisearchable against: [ :name, :period ]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :artefact
  has_one_attached :photo

  validates :date, presence: true
  validates :description, presence: true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/museum.rb
class Museum < ApplicationRecord
  has_many :artefacts
  has_one_attached :photo

  validates :name, presence: true
  validates :location, presence: true

  include PgSearch::Model
  multisearchable against: [ :name, :location ]
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :submissions
  has_many :favorites
  has_one_attached :photo

  acts_as_favoritor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end

  private

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
  end
end

app/controllers/artefacts_controller.rb
class ArtefactsController < ApplicationController
  before_action :authenticate_user!, only: :toggle_favorite
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @artefacts = []
    @collections = []
    @museums = []
    if params[:query].present?
      results = PgSearch.multisearch(params[:query])
      results.each do |result|
        @artefacts << result.searchable if result.searchable_type == "Artefact"
        @collections << result.searchable if result.searchable_type == "Collection"
        @museums << result.searchable if result.searchable_type == "Museum"
      end
    else
       @artefacts = Artefact.all
       @collections = Collection.all
       @museums = Museum.all
    end
  end

  def show
    @artefact = Artefact.find(params[:id])
  end

  def toggle_favorite
    @artefact = Artefact.find_by(id: params[:id])
    current_user.favorited?(@artefact) ?
    current_user.unfavorite(@artefact) :
    current_user.favorite(@artefact)
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def show
    @collection = Collection.find(params[:id])
    # @artefacts = Artefact.where(collection: @collection)
    @artefacts = @collection.artefacts


    @markers = @artefacts.geocoded.map do |artefact|
      {
        lat: artefact.latitude,
        lng: artefact.longitude,
        info_window: render_to_string(partial: "info_window", locals: { artefact: artefact }),
        image_url:  helpers.asset_url('sa-marker_sred3.png')
      }
    end

     @markers << {
        lat: @collection.latitude,
        lng: @collection.longitude,
        info_window: render_to_string(partial: "info_window_collection", locals: { collection: @collection }),
        image_url:  helpers.asset_url('sa-marker_ablue3.png')
      }
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @artefact = Artefact.find(params[:artefact_id])
    @events = @artefact.events
  end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def show
    @museum = Museum.find(params[:id])
    @artefacts = @museum.artefacts
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def create
    @submission = Submission.new(submission_params)
    @submission.user = current_user
    if @submission.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def submission_params
    params.require(:submission).permit(:description, :name, :origin_year,
    :origin_location, :current_location, :context, :made_by, :material,
    :registration_num)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @submission = Submission.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/artefacts/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1544011431-abf089b738b5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80);">
  <div class="container">
    <h1 class="artefact-index">Explore Stolen Artefacts</h1>
  </div>
</div>

<div class="container">

  <% if @collections.count >= 1 %>
    <h2 class="d-flex justify-content-center index-header">Artefacts</h2>
    <div class="cards-artefacts" >
      <% @artefacts.first(8).each do |artefact| %>
        <div class="card-artefact">
          <%= cl_image_tag artefact.photo.key %>
          <div class="card-artefact-infos">
           <%= link_to(artefact_path(artefact), class: "link-to-text :hover") do %>
            <h2><%= artefact.name %></h2>
            <% end %>
            <p><%= "Origin: #{artefact.origin_location}" %></p>
            <p><%= "Currently: #{artefact.current_location}" %></p>
            <div class="card-icons">
              <a class="btn twitter-icon"
                href="https://twitter.com/intent/tweet?text=Find out how the <%= artefact.name %> came to be at the <%= artefact.current_location %>.&url=<%= artefact_url(artefact, protocol: 'https') %>&hashtags=stolenartefact,decolonizemuseums"
                target="_blank"><i class="fab fa-twitter"></i></a>
              <% if user_signed_in? %>
                <% if current_user.favorited?(artefact) %>
                  <div class="card-like"><%= link_to ("<i class='fas fa-heart like-icon red' data-id='#{artefact.id}'></i>").html_safe, toggle_favorite_artefact_path(artefact), remote: true, method: :post %></div>
                <% else %>
                  <div class="card-like"><%= link_to ("<i class='far fa-heart like-icon gray' data-id='#{artefact.id}'></i>").html_safe, toggle_favorite_artefact_path(artefact), remote: true, method: :post %></div>
                <% end %>
              <% else %>
                <div class="card-like"><%= link_to ("<i class='far fa-heart like-icon gray' data-id='#{artefact.id}'></i>").html_safe, new_user_session_path, method: :post %></div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <br>

  <% if @collections.count >= 1 %>
    <h2 class="d-flex justify-content-center index-header">Collections</h2>
    <div class="cards-collections">
      <% @collections.first(3).each do |collection| %>
        <div class="card-artefact">
        <%= cl_image_tag collection.photo.key %>
          <div class="card-artefact-infos">
            <%= link_to(collection_path(collection), class: "link-to-text :hover") do %>
            <h2><%= collection.name %></h2>
            <% end %>
            <p><%= "#{collection.period}" %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <br>

  <% if @museums.count >= 1 %>
    <h2 class="d-flex justify-content-center index-header">Museums</h2>
    <div class="cards-museums">
      <% @museums.first(3).each do |museum| %>
        <div class="card-artefact">
        <%= cl_image_tag museum.photo.key %>
          <div class="card-artefact-infos">
            <%= link_to(museum_path(museum), class: "link-to-text :hover") do %>
            <h2><%= museum.name %></h2>
            <% end %>
            <p><%= "#{museum.location}" %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="mb-5"></div>

app/views/artefacts/show.html.erb
<div class="top-0 left-0 d-flex position-absolute h-100 border-box">
  <div class="w-50 border-dark border-right">
  </div>
  <div class="w-50">
  </div>
</div>

<div class="parallax">
  <div class="parallax__group">
    <header>
      <div class="text-center text-white">
        <div class="d-inline-flex mb-2 mt-5 main-title">
          <h1 class="mr-2 mb-2"><%= @artefact.name %></h1>
          <% if current_user.favorited?(@artefact) %>
            <div><%= link_to ("<i class='fas fa-heart like-icon red' data-id='#{@artefact.id}'></i>").html_safe, toggle_favorite_artefact_path(@artefact), remote: true, method: :post %></div>
          <% else %>
            <div><%= link_to ("<i class='far fa-heart like-icon gray' data-id='#{@artefact.id}'></i>").html_safe, toggle_favorite_artefact_path(@artefact), remote: true, method: :post %></div>
          <% end %>
        </div>
        <br>
        <div class="locations d-inline-flex">
          <div><h3><%= @artefact.origin_location %></h3></div>
          <div class="current-location ml-2 border-left border-danger px-2"><h4><%= @artefact.current_location %></h4></div>
        </div>
        <div class="artefact-details">
          <p>
            The <%= @artefact.name %> is currently on display at <%= @artefact.current_location %>. Its provenance can be traced back to <%= @artefact.origin_location %>, <%= @artefact.origin_year %>, made by the <%= @artefact.made_by %> people to <%= @artefact.context %>.
            <%= link_to "View the Collection".upcase, collection_path(@artefact.collection.id) %>
          </p>
        </div>
      </div>
    </header>
  </div>

  <% @artefact.events.each do |event| %>
    <div class="parallax__group d-flex align-items-center">
      <div class="parallax__layer parallax__layer--image d-flex ml-2">
        <%= cl_image_tag event.photo.key %>
      </div>
      <div class="parallax__layer parallax__layer--dot d-flex justify-content-center"><h3> • </h3></div>
      <div class="parallax__layer parallax__layer--text">
        <div class="text-card ml-4">
          <h2><%= event.date %></h2>
          <p><%= event.description %></p>
        </div>
      </div>
    </div>
    <div class="h-20"></div>
  <% end %>
  <div class="view-more d-flex justify-content-center collection-button">
    <%= link_to "Learn more about the Collection", collection_path(@artefact.collection.id) %>
  </div>
</div>

app/views/artefacts/toggle_favorite.js.erb
var artefactId = '<%= @artefact.id%>'
function toggleLikeButton(artefactId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${artefactId}']`)
  likeButton.classList.toggle('gray');
  likeButton.classList.toggle('red');
  likeButton.classList.toggle('fas');
  likeButton.classList.toggle('far');
  console.log('clicked');
}
toggleLikeButton(artefactId);

app/views/collections/_info_window.html.erb
<div class="card-marker">
  <h2><%= artefact.name %></h2>
  <p>Current Location:
  <br>
  <%= artefact.current_location %></p>
  <button type="button" class="btn btn-primary"><%= link_to "View the Museum", museum_path(artefact.museum) %></button>
</div>

app/views/collections/_info_window_collection.html.erb
<div class="card-marker">
  <h2><%= @collection.name %></h2>
  <p>Origin Location:
  <br>
  <%= @collection.origin_location %></p>
</div>

app/views/collections/show.html.erb
<div class="banner banner-collection" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
url(https://static01.nyt.com/images/2020/01/29/opinion/29Ehikhamenor1/merlin_165734295_cd0ed8e7-66c6-4301-ace8-4665ad821374-superJumbo.jpg);">
  <div class="collection-title text-center text-white">
    <div class="mb-2 mt-5 main-title">
      <h1 class="mr-2 mb-2"><%= @collection.name %></h1>
      <h3>The Collection</h3>
    </div>
  </div>
</div>



<div class="opening-section mt-5">
    <div class="collection-introduction">
      <h3>What are they?</h3>
      <p><%= @collection.introduction %></p>
    </div>
    <div class="collection-box">
      <div class="flex-item"><h3>Origin Location:</h3><p><%= @collection.origin_location %></p></div>
      <div class="flex-item"><h3>Period:</h3><p><%= @collection.period %></p></div>
      <div class="flex-item"><h3>Total number of artefacts in this collection worldwide:</h3><p><%= @collection.number_of_artefacts %></p></div>
      <div class="flex-item"><h3>Number of museums who own <%= @collection.name %>:</h3><p><%= @collection.number_of_museums %></p></div>
    </div>
</div>

<div class="collection-map mt-5">
    <div class="show-map"
       id="map"
       style="width: 80%; height: 598px; margin: 0 auto;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

<div class="context-container mt-5 d-flex">
  <div class="collection-context">
    <h3 class="text-center">Further context</h3>
    <p><%= @collection.context %></p>
  </div>
</div>

<div class="container">
  <h2 class="collection-renowned-works">Renowned artefacts from <%= @collection.name%></h2>
  <div class="cards-collection-artefacts mb-5">
    <% @artefacts.first(6).each do |artefact| %>
      <div class="card-artefact">
        <%= cl_image_tag artefact.photo.key %>
        <div class="card-artefact-infos">
          <%= link_to(artefact_path(artefact), class: "link-to-text :hover") do %>
          <h2><%= artefact.name %></h2>
          <% end %>
          <p><%= "Origin: #{artefact.origin_location}, #{artefact.origin_year}" %></p>
          <p><%= "Currently: #{artefact.current_location}" %></p>
          <div class="card-icons">
            <a class="btn twitter-icon"
              href="https://twitter.com/intent/tweet?text=Find out how the <%= artefact.name %> came to be at the <%= artefact.current_location %>.&url=<%= artefact_url(artefact, protocol: 'https') %>&hashtags=stolenartefact,decolonizemuseums"
              target="_blank"><i class="fab fa-twitter"></i></a>
            <% if current_user.favorited?(artefact) %>
              <div class="card-like"><%= link_to ("<i class='fas fa-heart like-icon red' data-id='#{artefact.id}'></i>").html_safe, toggle_favorite_artefact_path(artefact), remote: true, method: :post %></div>
            <% else %>
              <div class="card-like"><%= link_to ("<i class='far fa-heart like-icon gray' data-id='#{artefact.id}'></i>").html_safe, toggle_favorite_artefact_path(artefact), remote: true, method: :post %></div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/museums/show.html.erb
<div class="bottom-container" style="background-image: url( <%= image_path "bm_coverillus_v1a.svg" %>)">
 <div class="el" style="background-image: url( <%= image_path "bm_artefacts_v1a.svg" %>)"></div>
</div>

<div class="container">
  <h1 class="museum-title mb-5"><%= "The #{@museum.name}" %></h1>

  <div class="row mb-5">
    <div class="col-6 museum-infos">
      <div class="card-museum">
        <img src="https://images.unsplash.com/photo-1574515529318-b3a2cd51242e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2051&q=80" alt="british museum">
        <div class="card-museum-infos">
          <div>
            <p><strong>Founded: </strong><%= @museum.founded %></p>
            <p><strong>Opened: </strong><%= @museum.opened %></p>
            <p><strong>Annual Visitors: </strong><%= " #{@museum.visitors_per_year.to_f} million" %></p>
            <p><strong>Annual Admissions Income: </strong><%= " £#{@museum.income} million" %></p>
            <p><strong>Public Funding: </strong><%= @museum.funding %></p>
            <p><strong>Current Director: </strong><%= @museum.director %></p>
          </div>
        </div>
        <div class="col-12 mb-2">
          <h3 class="text-center">Museum Governance</h3>
            <div class="d-inline-flex col-6">
              <img src="https://res.cloudinary.com/dfkhcr30g/image/upload/v1623939055/Infographics/bm_trustees_sex_v2_knye7y.png" alt="gender info graphic">
              <img src="https://res.cloudinary.com/dfkhcr30g/image/upload/v1623939055/Infographics/bm_trustees_ethnicity_v2_ufpmi9.png" alt="ethnicity info graphic">
            </div>
        </div>
        <div class="col-12 mb-2">
          <h3 class="text-center">Museum Collection Origins</h3>
        <div class="d-inline-flex col-6">
          <!-- <div class="d-inline-flex"> -->
            <img src="https://res.cloudinary.com/dfkhcr30g/image/upload/v1623939055/Infographics/bm_artefacts_inventory_v2_lwdmhg.png" alt="inventory info graphic">
            <img src="https://res.cloudinary.com/dfkhcr30g/image/upload/v1623939055/Infographics/bm_artefacts_origin_v2_edlrrk.png" alt="origin info graphic">
          </div>
        </div>
          </div>
    </div>

    <div class="col-6">
      <div>
        <% @artefacts.first(6).each do |artefact| %>
          <div class="card-artefact">
            <%= cl_image_tag artefact.photo.key %>
            <div class="card-artefact-infos">
              <%= link_to(artefact_path(artefact), class: "link-to-text :hover") do %>
                <h2><%= artefact.name %></h2>
              <% end %>
              <p><%= "Origin: #{artefact.origin_location}, #{artefact.origin_year}" %></p>
              <p><%= "Currently: #{artefact.current_location}" %></p>
              <div class="card-icons">
                <a class="btn twitter-icon"
                  href="https://twitter.com/intent/tweet?text=Find out how the <%= artefact.name %> came to be at the <%= artefact.current_location %>.&url=<%= artefact_url(artefact, protocol: 'https') %>&hashtags=stolenartefact,decolonizemuseums"
                  target="_blank"><i class="fab fa-twitter"></i></a>
                <% if current_user.favorited?(artefact) %>
                  <div class="card-like"><%= link_to ("<i class='fas fa-heart like-icon red' data-id='#{artefact.id}'></i>").html_safe, toggle_favorite_artefact_path(artefact), remote: true, method: :post %></div>
                <% else %>
                  <div class="card-like"><%= link_to ("<i class='far fa-heart like-icon gray' data-id='#{artefact.id}'></i>").html_safe, toggle_favorite_artefact_path(artefact), remote: true, method: :post %></div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="push footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/stolenartefacts/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/stolenartefact/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/StolenArtefact"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-artefact" style="background-color: $black; color: $red;">
  <div class="d-flex align-items-center">
    <%= link_to root_path, class: "navbar-brand p-3" do %>
      <%= image_tag "SA_logo3.png" %>
      <% end %>

    <div class="form-inline py-4">
      <%= form_tag artefacts_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: ""
      %>
      <%= submit_tag "Search", class: "btn" %>
      <% end %>
    </div>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse mr-2" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
          <div class="artefacts-click">
            <%= link_to "View All Artefacts", artefacts_path %>
          </div>
        </li>

        <li class="nav-item dropdown pr-4">
            <% if current_user.photo.attached? %>
              <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown" %>
              </a>
            <% else %>
              <a class="nav-link avatar-no-image" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name[0] %>
              </a>
            <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
url(https://images.unsplash.com/photo-1578163678052-eef169544f75?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80);">
</div>

<div class="container profile-container profile-text">
  <h2><%= "#{@user.name.capitalize}'s Collection" %></h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <% @user.all_favorited.each do |artefact| %>
        <div class="card-artefact">
          <%= cl_image_tag artefact.photo.key %>
          <div class="card-artefact-infos">
            <%= link_to(artefact_path(artefact), class: "link-to-text :hover") do %>
            <h2><%= artefact.name %></h2>
            <% end %>
            <p><%= "Originated: #{artefact.origin_location}, #{artefact.origin_year}" %>
            <%= "Current Location: #{artefact.current_location}" %></p>
            <div class="card-icons">
              <a class="btn twitter-icon"
                href="https://twitter.com/intent/tweet?text=Find out how the <%= artefact.name %> came to be at the <%= artefact.current_location %>.&url=<%= artefact_url(artefact, protocol: 'https') %>&hashtags=stolenartefact,decolonizemuseums"
                target="_blank"><i class="fab fa-twitter"></i></a>
              <% if current_user.favorited?(artefact) %>
                <div class="card-like"><%= link_to ("<i class='fas fa-heart like-icon red' data-id='#{artefact.id}'></i>").html_safe, toggle_favorite_artefact_path(artefact), remote: true, method: :post %></div>
              <% else %>
                <div class="card-like"><%= link_to ("<i class='far fa-heart like-icon gray' data-id='#{artefact.id}'></i>").html_safe, toggle_favorite_artefact_path(artefact), remote: true, method: :post %></div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-12 col-lg-6 form">
      <div class="form-submission">
        <h4 class="mb-2 mt-2">Contact Us</h4>
        <p><i>Do you have more information about any of the artefacts on our site? Is there another artefact we should add? Let us know and our team of experts will look into it.</i></p>
        <%= simple_form_for(@submission) do |f| %>
          <%= f.input :name, label: "Artefact Name" %>
          <%= f.input :description %>
          <%= f.input :current_location, label: "Where did you see it?" %>
          <div class="row">
            <div class="col"><%= f.input :origin_location, label: "Where was it made?" %></div>
            <div class="col"><%= f.input :origin_year, label: "When was it made?" %></div>
          </div>
          <div class="row">
            <div class="col"><%= f.input :made_by, label: "Who made it?" %></div>
            <div class="col"><%= f.input :material, label: "What materials was it made from?" %></div>
          </div>
          <%= f.input :context, collection: ['Domestic', 'Religious', 'Burial', 'Artistic', 'Farming', 'Military', 'Other'], label: "What was it used for?" %>
          <%= f.button :submit, :style => "display: none;", id: "real-form-submission" %>
          <button id="sweet-alert-submission" class="btn btn-dark">Submit</button>
        <% end %>
      </div>
    </div>
  </div>
</div>